import './globals.css'

import Header from '../components/header/Header'
import Footer from '../components/footer/Footer'
import ReduxProvider from '@/components/redux-provider'

export const metadata = {
  title: 'Mirae real estate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          src="//dapi.kakao.com/v2/maps/sdk.js?appkey=bc9a1a6e3d248caad693cd88df390c11&libraries=services"
        ></script>
      </head>
      <body>
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  )
}
