import './globals.css'
import { Inter } from 'next/font/google'

import Header from '../components/header/Header'
import Footer from '../components/footer/Footer'
import ReduxProvider from '@/components/redux-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mirae real estate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider >
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  )
}
